import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Panel, PanelGroup, PanelResizeHandle, } from "react-resizable-panels";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useUiStore } from "../stores/uiStore";
import { StatusBar } from "./StatusBar";
export function WorkspaceLayout({ sidebar, center, inspector, }) {
    const sidebarCollapsed = useUiStore((s) => s.sidebarCollapsed);
    const inspectorCollapsed = useUiStore((s) => s.inspectorCollapsed);
    const centerMaximized = useUiStore((s) => s.centerMaximized);
    const toggleSidebar = useUiStore((s) => s.toggleSidebar);
    const toggleInspector = useUiStore((s) => s.toggleInspector);
    const hideSide = centerMaximized || sidebarCollapsed;
    const hideInsp = centerMaximized || inspectorCollapsed;
    return (_jsxs("div", { className: "flex min-h-0 flex-1 flex-col", children: [_jsxs("div", { className: "relative min-h-0 flex-1", children: [_jsxs(PanelGroup, { direction: "horizontal", autoSaveId: "oridb-workspace-panels", children: [!hideSide && (_jsxs(_Fragment, { children: [_jsx(Panel, { defaultSize: 18, minSize: 12, maxSize: 35, children: _jsx("div", { className: "bg-surface-elevated flex h-full flex-col shadow-sm", children: sidebar }) }), _jsx(PanelResizeHandle, { className: "bg-border hover:bg-primary w-1 transition-colors duration-150" })] })), _jsx(Panel, { minSize: 40, children: _jsx("div", { className: "flex h-full min-h-0 flex-col", children: center }) }), !hideInsp && (_jsxs(_Fragment, { children: [_jsx(PanelResizeHandle, { className: "bg-border hover:bg-primary w-1 transition-colors duration-150" }), _jsx(Panel, { defaultSize: 22, minSize: 15, maxSize: 40, children: _jsx("div", { className: "bg-surface-elevated flex h-full flex-col shadow-sm", children: inspector }) })] }))] }), !hideSide && (_jsx("button", { type: "button", title: "Toggle sidebar (Cmd+B)", "aria-label": "Toggle sidebar", className: "border-border bg-surface-elevated text-text-muted hover:text-text-primary absolute top-2 left-0 z-10 rounded-r border border-l-0 p-0.5 transition-colors duration-150", onClick: toggleSidebar, children: _jsx(ChevronLeft, { className: "h-4 w-4" }) })), hideSide && (_jsx("button", { type: "button", title: "Show sidebar", "aria-label": "Show sidebar", className: "border-border bg-surface-elevated text-text-muted absolute top-2 left-0 z-10 rounded border p-0.5", onClick: toggleSidebar, children: _jsx(ChevronRight, { className: "h-4 w-4" }) })), !hideInsp && (_jsx("button", { type: "button", title: "Toggle inspector (Cmd+J)", "aria-label": "Toggle inspector", className: "border-border bg-surface-elevated text-text-muted hover:text-text-primary absolute top-2 right-0 z-10 rounded-l border border-r-0 p-0.5 transition-colors duration-150", onClick: toggleInspector, children: _jsx(ChevronRight, { className: "h-4 w-4" }) })), hideInsp && (_jsx("button", { type: "button", title: "Show inspector", "aria-label": "Show inspector", className: "border-border bg-surface-elevated text-text-muted absolute top-2 right-0 z-10 rounded border p-0.5", onClick: toggleInspector, children: _jsx(ChevronLeft, { className: "h-4 w-4" }) }))] }), _jsx(StatusBar, {})] }));
}
